version: '3'
services:
  corsproxy:
    build: .
    image: cors-anywhere
    restart: always
    ports:
    - "8080:8080"
    # If you use jwilder/nginx-proxy and letsencrypt
    #environment:
    #- VIRTUAL_HOST=<YOUR DOMAIN>
    #- VIRTUAL_PORT=8080
    #- LETSENCRYPT_HOST=<YOUR DOMAIN>
    #- LETSENCRYPT_EMAIL=
    networks:
    - proxy

networks:
  proxy:
